# Generated by Django 2.2.1 on 2019-05-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('item', models.CharField(max_length=30)),
                ('topping1', models.CharField(max_length=16)),
                ('topping2', models.CharField(max_length=16)),
                ('topping3', models.CharField(max_length=16)),
                ('extra_kaas', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
