# Generated by Django 2.2.1 on 2019-05-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=30)),
                ('product', models.CharField(max_length=30)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='item',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.FloatField(),
        ),
    ]
