# Generated by Django 2.2.1 on 2019-05-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190524_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='toppings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
