# Generated by Django 2.2.1 on 2019-05-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_products_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='topping1',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='topping2',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='topping3',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
