# Generated by Django 2.2.1 on 2019-05-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190527_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('product', models.CharField(max_length=40)),
                ('price', models.FloatField()),
            ],
        ),
    ]
